import { _electron as electron, expect } from '@playwright/test'
import { mkdtempSync, mkdirSync, readFileSync, readdirSync } from 'node:fs'
import { resolve, join } from 'node:path'
import { generateKeyPairSync } from 'node:crypto'
import { once } from 'node:events'
import ssh2 from 'ssh2'

const root = resolve('.')
mkdirSync(join(root, '.test-data'), { recursive: true })
const directory = mkdtempSync(join(root, '.test-data', 'operations-'))
const environment = { ...process.env, NODUS_TEST_DATA: directory }
delete environment.ELECTRON_RUN_AS_NODE; delete environment.NODUS_DEV
const key = generateKeyPairSync('rsa', { modulusLength: 2048 }).privateKey.export({ type: 'pkcs1', format: 'pem' }).toString()
const clients = new Set()
const commands = []
const inputs = []
let content = Buffer.from('ilk sürüm\r\n')
const server = new ssh2.Server({ hostKeys: [key] }, (client) => {
  clients.add(client); client.on('error', () => {}); client.on('close', () => clients.delete(client))
  client.on('authentication', (context) => context.method === 'password' && context.password === 'fixture-password' ? context.accept() : context.reject(['password']))
  client.on('ready', () => client.on('session', (accept) => {
    const session = accept()
    session.on('pty', (acceptPty) => acceptPty?.()); session.on('window-change', (acceptResize) => acceptResize?.())
    session.on('exec', (acceptExec, _reject, info) => {
      commands.push(info.command)
      const stream = acceptExec(); stream.on('error', () => {})
      if (info.command.startsWith('tmux new-session')) { stream.write('Kalıcı oturum\r\n'); stream.on('data', (chunk) => inputs.push(chunk.toString())); return }
      if (/^(tail |docker logs |journalctl )/.test(info.command)) { stream.write('INFO başladı\nERROR örnek hata\nWARN gecikme\n'); return }
      if (info.command.startsWith('docker ps')) stream.write(JSON.stringify({ ID: 'container-one', Names: 'web', State: 'running', Image: 'nginx:fixture' }) + '\n')
      else if (info.command.includes('systemctl list-units')) stream.write('nginx.service loaded active running Web server\n')
      else if (info.command.startsWith('sh -c ')) stream.write('Akış fixture çıktısı\n')
      stream.exit(0); stream.end()
    })
    session.on('sftp', (acceptSftp) => {
      const sftp = acceptSftp(); const directories = new Set(); let handleIndex = 0
      const attrs = () => ({ mode: 0o100644, size: content.length, uid: 1000, gid: 1000, atime: 1700000000, mtime: 1700000000 })
      sftp.on('REALPATH', (request) => sftp.name(request, [{ filename: '/fixture', longname: '', attrs: { ...attrs(), mode: 0o40755 } }]))
      sftp.on('OPENDIR', (request) => sftp.handle(request, Buffer.from('directory-' + handleIndex++)))
      sftp.on('READDIR', (request, handle) => { if (directories.has(handle.toString())) { sftp.status(request, 1); return } directories.add(handle.toString()); sftp.name(request, [{ filename: 'app.conf', longname: '', attrs: attrs() }]) })
      for (const operation of ['STAT', 'LSTAT', 'FSTAT']) sftp.on(operation, (request) => sftp.attrs(request, attrs()))
      sftp.on('OPEN', (request, _path, flags) => { if (flags & 16) content = Buffer.alloc(0); sftp.handle(request, Buffer.from('file')) })
      sftp.on('READ', (request, _handle, offset, length) => offset >= content.length ? sftp.status(request, 1) : sftp.data(request, content.subarray(offset, offset + length)))
      sftp.on('WRITE', (request, _handle, offset, data) => { const next = Buffer.alloc(Math.max(content.length, offset + data.length)); content.copy(next); data.copy(next, offset); content = next; sftp.status(request, 0) })
      sftp.on('CLOSE', (request) => sftp.status(request, 0))
    })
  }))
})
server.listen(0, '127.0.0.1'); await once(server, 'listening')
let application
try {
  application = await electron.launch({ args: ['.'], cwd: root, env: environment })
  const page = await application.firstWindow()
  const failures = []; page.on('pageerror', (error) => failures.push(error.message))
  await page.getByLabel('Kasa parolası', { exact: true }).fill('isolated-operations-vault')
  await page.getByLabel('Parolayı doğrula').fill('isolated-operations-vault')
  await page.getByRole('button', { name: 'Şifreli kasamı oluştur', exact: true }).click()
  await application.evaluate(({ dialog }) => { globalThis.approvals = []; globalThis.acceptOperation = true; dialog.showMessageBox = async (_window, options) => { globalThis.approvals.push(options); return { response: globalThis.acceptOperation ? 1 : 0, checkboxChecked: false } } })
  await page.getByRole('button', { name: 'Yeni sunucu', exact: true }).click()
  await page.getByLabel('Sunucu adı', { exact: true }).fill('Üretim fixture')
  await page.getByLabel('Adres', { exact: true }).fill('127.0.0.1')
  await page.getByLabel('Port', { exact: true }).fill(String(server.address().port))
  await page.getByLabel('Sunucu parolası', { exact: true }).fill('fixture-password')
  await page.getByLabel('Parolayı kasaya kaydet', { exact: true }).check()
  await page.getByLabel('Üretim sunucusu:', { exact: false }).check()
  await page.getByLabel('Kesintiye dayanıklı oturum (tmux)', { exact: true }).check()
  await page.getByRole('button', { name: 'Kaydet ve bağlan', exact: true }).click()
  await expect(page.locator('.terminal-guard')).toBeVisible()
  const id = await page.evaluate(() => document.querySelector('.workspace')?.getAttribute('aria-label'))
  expect(id).toContain('Üretim fixture')
  await page.getByRole('button', { name: 'Üretim terminalini aç', exact: true }).click()
  await expect(page.locator('.terminal-guard')).toHaveCount(0)
  await page.getByTestId('terminal').locator('textarea').focus(); await page.keyboard.type('echo ready'); await page.keyboard.press('Enter')
  await expect.poll(() => inputs.join('')).toContain('echo ready')
  await page.getByRole('button', { name: 'Sunucu yönetimi', exact: true }).click()
  await expect(page.locator('.managed-list')).toContainText('web')
  await application.evaluate(() => { globalThis.acceptOperation = false })
  await page.getByRole('button', { name: 'Yeniden başlat', exact: true }).click()
  await expect(page.locator('.operations-panel [role=alert]')).toContainText('iptal')
  expect(commands.some((command) => command.startsWith('docker restart'))).toBe(false)
  await application.evaluate(() => { globalThis.acceptOperation = true })
  await page.getByRole('button', { name: 'Yeniden başlat', exact: true }).click()
  await expect.poll(() => commands.includes("docker restart -- 'container-one'")).toBe(true)
  await page.getByRole('button', { name: 'Servisler', exact: true }).click()
  await expect(page.locator('.managed-list')).toContainText('nginx.service')
  await page.getByRole('button', { name: 'Günlük', exact: true }).click()
  await expect(page.getByLabel('Canlı günlük çıktısı')).toContainText('örnek hata')
  await page.getByLabel('Günlük seviyesi').selectOption('error')
  await expect(page.getByLabel('Canlı günlük çıktısı')).not.toContainText('başladı')
  await page.getByLabel('Günlük dosyası yolu').fill('/var/log/app.log')
  await page.getByRole('button', { name: 'Dosyayı izle', exact: true }).click()
  await expect(page.locator('.log-tabs > div')).toHaveCount(2)
  await page.screenshot({ path: join(directory, 'logs.png') })
  await page.getByRole('button', { name: 'Terminale dön', exact: true }).click()
  await page.getByRole('button', { name: 'Kestirmeler', exact: true }).click()
  await page.getByRole('button', { name: 'Yeni kestirme', exact: true }).click()
  await page.getByLabel('Ad', { exact: true }).fill('Parametre fixture')
  await page.getByLabel('Parametreli komut akışı', { exact: true }).check()
  await page.getByLabel('Komut', { exact: true }).fill('printf %s {{mesaj}}')
  await page.getByRole('button', { name: 'Kestirmeyi kaydet', exact: true }).click()
  await page.getByRole('button', { name: 'Parametre fixture çalıştır', exact: true }).click()
  await page.getByLabel('mesaj', { exact: true }).fill('Türkçe değer')
  await page.getByRole('button', { name: 'Önizlemeyi onayla ve çalıştır', exact: true }).click()
  await expect(page.getByLabel('Akış sonucu')).toContainText('tamamlandı')
  expect(commands.some((command) => command.startsWith('sh -c ') && command.includes('Türkçe değer'))).toBe(true)
  await page.screenshot({ path: join(directory, 'workflow.png') })
  await page.getByRole('dialog').getByRole('button', { name: 'Kapat', exact: true }).click()
  await page.locator('.session-tab').filter({ hasText: 'Üretim fixture' }).click()
  await page.locator('.file-name').filter({ hasText: 'app.conf' }).dblclick()
  await page.getByLabel('Dosya içeriği').fill('yeni sürüm\n')
  await page.getByLabel('Dosya içeriği').press('Control+s')
  await page.getByRole('button', { name: 'Değişiklikleri kaydet', exact: true }).click()
  await expect.poll(() => content.toString()).toBe('yeni sürüm\r\n')
  const historyDirectory = join(directory, 'file-history')
  expect(readdirSync(historyDirectory)).toHaveLength(1)
  expect(readFileSync(join(historyDirectory, readdirSync(historyDirectory)[0]), 'utf8')).not.toContain('ilk sürüm')
  await page.getByRole('button', { name: 'Fark / Geçmiş', exact: true }).click()
  await page.getByLabel('Karşılaştırılacak sürüm').selectOption({ index: 1 })
  await page.getByRole('button', { name: 'Bu sürüme geri dön', exact: true }).click()
  await expect.poll(() => content.toString()).toBe('ilk sürüm\r\n')
  await page.getByLabel('Dosya içeriği').fill('çakışma denemesi')
  content = Buffer.from('başka kullanıcı değiştirdi\r\n')
  await page.getByLabel('Dosya içeriği').press('Control+s')
  await page.getByRole('button', { name: 'Değişiklikleri kaydet', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('sunucuda değişmiş')
  expect(content.toString()).toBe('başka kullanıcı değiştirdi\r\n')
  await page.getByRole('dialog').getByRole('button', { name: 'Vazgeç', exact: true }).click()
  for (const client of clients) client.end()
  await expect(page.locator('.session-controls')).toContainText('Bağlantı kapalı')
  await expect.poll(() => commands.filter((command) => command.startsWith('tmux new-session')).length, { timeout: 15000 }).toBe(2)
  await expect(page.locator('.terminal-guard')).toBeVisible()
  await expect(page.getByLabel('Dosya içeriği')).toHaveValue('çakışma denemesi')
  await page.screenshot({ path: join(directory, 'production.png') })
  expect((await application.evaluate(() => globalThis.approvals)).some((approval) => approval.message.includes('ÜRETİM') && approval.detail.includes('docker restart'))).toBe(true)
  await page.evaluate(() => window.nodus.lock())
  await expect(page.getByLabel('Kasa parolası', { exact: true })).toBeVisible()
  const connectionsBefore = commands.filter((command) => command.startsWith('tmux new-session')).length
  await new Promise((resolveDelay) => setTimeout(resolveDelay, 2500))
  expect(commands.filter((command) => command.startsWith('tmux new-session')).length).toBe(connectionsBefore)
  expect(failures).toEqual([])
  console.log('PASS: production approval/cancel, Docker/systemd, multiple live logs, parameter workflow, real SFTP encrypted backup/restore/conflict, tmux reconnect and lock cleanup. Screenshots: ' + directory)
} finally {
  await application?.close(); for (const client of clients) client.end()
  await new Promise((resolveClose) => server.close(resolveClose))
}
