import { expect } from '@playwright/test'
import { join } from 'node:path'

export async function testPersonalization(application, page, directory) {
  const workspace = page.locator('.workspace:not(.inactive)')
  const sidebar = page.locator('#workspace-sidebar')
  await expect(page.locator('.app')).toHaveClass(/focus-mode/)
  await page.mouse.move(650, 350)
  await expect(sidebar).toBeHidden()
  const originalLeft = (await workspace.boundingBox()).x
  await page.getByRole('button', { name: 'Sol menüyü aç', exact: true }).hover()
  await expect(sidebar).toBeVisible()
  await expect.poll(async () => (await sidebar.boundingBox()).x).toBe(65)
  expect((await workspace.boundingBox()).x).toBe(originalLeft)
  await sidebar.hover()
  await page.mouse.move(650, 350)
  await expect(sidebar).toBeHidden()
  await page.getByRole('button', { name: 'Menüyü aç', exact: true }).click()
  await expect(sidebar).toBeVisible()
  await sidebar.getByRole('button', { name: 'Hızlı erişim' }).focus()
  await page.keyboard.press('Escape')
  await expect(sidebar).toBeHidden()

  await application.evaluate(({ ipcMain }) => {
    globalThis.personalizationEvents = []
    ipcMain.on('ssh:input', (_event, id, data) => globalThis.personalizationEvents.push({ id, data }))
  })
  await page.getByRole('button', { name: 'Kestirmeler', exact: true }).click()
  await page.getByRole('button', { name: 'Yeni kestirme', exact: true }).click()
  await page.getByLabel('Ad', { exact: true }).fill('Panel denemesi')
  await page.getByLabel('Komut', { exact: true }).fill('echo panel-test')
  await page.getByLabel('Grup', { exact: true }).fill('Panel')
  await page.getByRole('button', { name: 'Kestirmeyi kaydet', exact: true }).click()
  await page.locator('.session-tab').getByRole('button', { name: '127.0.0.1', exact: true }).click()
  await expect(sidebar).toBeHidden()
  const files = workspace.locator('.sftp-slot')
  const initialHeight = (await files.boundingBox()).height
  const dock = workspace.getByRole('region', { name: 'Oturum kestirmeleri', exact: true })
  await dock.locator('.snippet-dock-toggle').click()
  await expect(dock.locator('.snippet-dock-toggle')).toHaveAttribute('aria-expanded', 'true')
  await expect.poll(async () => (await files.boundingBox()).height).toBeLessThan(initialHeight * 0.8)
  await dock.getByLabel('Oturum kestirmesi ara').fill('Panel denemesi')
  await dock.getByLabel('Oturum kestirme grubu').selectOption('Panel')
  await expect(dock.locator('.dock-snippet')).toHaveCount(1)
  await dock.getByRole('button', { name: 'Panel denemesi çalıştır', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('127.0.0.1')
  await page.getByRole('button', { name: 'Vazgeç', exact: true }).click()
  expect(await application.evaluate(() => globalThis.personalizationEvents.length)).toBe(0)
  await dock.getByRole('button', { name: 'Panel denemesi çalıştır', exact: true }).click()
  await page.getByRole('button', { name: 'Çalıştır', exact: true }).click()
  await expect.poll(() => application.evaluate(() => globalThis.personalizationEvents.map((event) => event.data))).toEqual(['echo panel-test\r'])

  await files.getByRole('listitem').filter({ has: page.getByRole('checkbox', { name: 'readme.txt seç', exact: true }) }).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Düzenle', exact: true }).click()
  await page.getByLabel('Dosya içeriği').fill('Unsaved while changing themes')
  const terminalElement = await workspace.locator('[data-testid="terminal"] .xterm').elementHandle()
  await page.getByRole('button', { name: 'Ayarlar', exact: true }).click()
  const appearance = page.getByRole('region', { name: 'Görünüm ayarları', exact: true })
  await expect(appearance.locator('.theme-card')).toHaveCount(8)
  const palettes = [['Nodus', 'nodus'], ['Nord', 'nord'], ['Dracula', 'dracula'], ['Orman', 'forest'], ['Okyanus', 'ocean'], ['Kehribar', 'amber'], ['Gül', 'rose'], ['Grafit', 'slate']]
  for (const [label, id] of palettes) {
    await appearance.getByRole('button', { name: label + ' paleti', exact: true }).click()
    await expect(page.locator('html')).toHaveAttribute('data-theme', id)
  }
  await appearance.getByRole('button', { name: 'Okyanus paleti', exact: true }).click()
  await appearance.getByRole('button', { name: 'Açık', exact: true }).click()
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(237, 247, 249)')
  await appearance.getByLabel('Arayüz yazı tipi', { exact: true }).selectOption('verdana')
  await appearance.getByLabel('Terminal ve editör yazı tipi', { exact: true }).selectOption('consolas')
  await appearance.getByLabel('Terminal yazı boyutu', { exact: true }).fill('18')
  await appearance.getByLabel('Terminal satır aralığı', { exact: true }).fill('1.7')
  await expect(page.locator('body')).toHaveCSS('font-family', /Verdana/)
  await expect(appearance.locator('.appearance-preview')).toHaveCSS('font-size', '18px')
  await appearance.scrollIntoViewIfNeeded()
  await page.screenshot({ path: join(directory, 'appearance-light.png') })
  await appearance.getByRole('button', { name: 'Sistem', exact: true }).click()
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-mode', 'dark')
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-mode', 'light')
  await appearance.getByRole('button', { name: 'Koyu', exact: true }).click()
  await page.locator('.session-tab').getByRole('button', { name: '127.0.0.1', exact: true }).click()
  expect(await terminalElement.evaluate((element) => element.isConnected)).toBe(true)
  await expect(page.getByLabel('Dosya içeriği')).toHaveValue('Unsaved while changing themes')
  await expect(page.getByLabel('Dosya içeriği')).toHaveCSS('font-size', '18px')
  await expect(workspace.locator('.xterm-rows').first()).toHaveCSS('font-size', '18px')
  await expect(workspace.locator('.xterm-viewport').first()).toHaveCSS('background-color', 'rgb(8, 24, 32)')
  await page.screenshot({ path: join(directory, 'personalized-workspace.png') })
  await page.getByRole('button', { name: 'Editörü kapat', exact: true }).click()
  await page.getByRole('button', { name: 'Değişiklikleri bırak', exact: true }).click()
  await dock.locator('.snippet-dock-toggle').click()
  await expect.poll(async () => (await files.boundingBox()).height).toBeGreaterThan(initialHeight * 0.9)
  await dock.locator('.snippet-dock-toggle').click()
  await page.getByRole('button', { name: 'Dosya panelini aç veya kapat', exact: true }).click()
  await expect(files).toBeHidden()
  await expect(dock.getByLabel('Oturum kestirmesi ara')).toBeVisible()
  await page.getByRole('button', { name: 'Dosya panelini aç veya kapat', exact: true }).click()
  await dock.locator('.snippet-dock-toggle').click()
  await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(800, 620))
  await expect(sidebar).toBeHidden()
  await page.getByRole('button', { name: 'Menüyü aç', exact: true }).click()
  await expect(sidebar).toBeVisible()
  await sidebar.getByRole('button', { name: 'Menüyü kapat', exact: true }).click()
  await expect(sidebar).toBeHidden()
  await page.screenshot({ path: join(directory, 'compact-workspace.png') })
  await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1440, 930))
  await page.getByRole('button', { name: 'Ayarlar', exact: true }).click()
  await appearance.getByRole('button', { name: 'Varsayılana dön', exact: true }).click()
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(11, 11, 13)')
  await expect(appearance.getByLabel('Terminal yazı boyutu', { exact: true })).toHaveValue('13')
  await appearance.getByRole('button', { name: 'Nord paleti', exact: true }).click()
  await appearance.getByLabel('Terminal yazı boyutu', { exact: true }).fill('16')
  await page.locator('.session-tab').getByRole('button', { name: '127.0.0.1', exact: true }).click()
  console.log('PASS: shared SFTP/snippet panel, confirmed command dispatch, hover/keyboard menu, eight themes, live fonts, preserved terminal/editor, compact layout, reset.')
}
